version: '3.8'

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env.local
    depends_on:
      - db
    networks:
      - backend-network

  db:
    container_name: db
    image: postgres:13
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  pgdata:

networks:
  backend-network:
    driver: bridge
