version: '3.8'

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-network
    command: >
      sh -c "npm run db:migrate && npm run db:seed && npm start"

  db:
    container_name: db
    image: postgres:13
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 2s
      retries: 5

volumes:
  pgdata:

networks:
  backend-network:
    driver: bridge
